### ISSUE TITLE
gradio 6.x breaks f5-tts

### ISSUE THREAD

**Issue by 6Morpheus6** [SWivid/F5-TTS#1239]
### Checks

- [x] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [x] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [x] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [x] I am using English to submit this issue to facilitate community communication.

### Environment Details

OS: Windows10
GPU: RTX 5080
Platform: Pinokio
Python 3.10.16

### Steps to Reproduce

1. Create a new environment
2. Activate the environment
3. Navigate to the project folder
4. Install pre-requirements
5. Install f5-tts
6. Start f5-tts

### ✔️ Expected Behavior

f5-tts starts

### ❌ Actual Behavior

Following error appears:

```
G:\pinokio\api\e2-f5-tts.git\app\env\Scripts\activate G:\pinokio\api\e2-f5-tts.git\app\env && f5-tts_infer-gradio
G:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'repr' attribute with value False was provided to the `Field()` function, which has no effect in the context it was used. '
repr' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a
 single member of a union type.
  warnings.warn(
G:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'frozen' attribute with value True was provided to the `Field()` function, which has no effect in the context it was used. 
'frozen' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached t
o a single member of a union type.
  warnings.warn(
Download Vocos from huggingface charactr/vocos-mel-24khz

vocab :  G:\pinokio\api\e2-f5-tts.git\app\src\f5_tts\infer\examples\vocab.txt
token :  custom
model :  G:\pinokio\api\e2-f5-tts.git\cache\HF_HOME\hub\models--SWivid--F5-TTS\snapshots\84e5a410d9cead4de2f847e7c9369a6440bdfaca\F5TTS_v1_Base\model_1250000.safetensors 

Traceback (most recent call last):
  File "G:\pinokio\bin\miniconda\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "G:\pinokio\bin\miniconda\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "G:\pinokio\api\e2-f5-tts.git\app\env\Scripts\f5-tts_infer-gradio.exe\__main__.py", line 4, in <module>
    from f5_tts.infer.infer_gradio import main
  File "G:\pinokio\api\e2-f5-tts.git\app\src\f5_tts\infer\infer_gradio.py", line 576, in <module>
    cherrypick_interface_multistyle = gr.Textbox(
  File "G:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\gradio\component_meta.py", line 194, in wrapper
    return fn(self, **kwargs)
TypeError: Textbox.__init__() got an unexpected keyword argument 'show_copy_button'

(env) (base) G:\pinokio\api\e2-f5-tts.git\app>
```

This error is caused by gradio 6.x because in pyproject.toml `gradio>=5.0.0` is requested
It fails with gradio 6.1 - 6.2
It works with gradio 5.50.0 with a non critical error.
It works without error up to gradio 5.49.1

**Comment by SWivid** [comment]
Hi @6Morpheus6 , thanks~
Fixed.

**Comment by 6Morpheus6** [comment]
Thank you @SWivid for the quick reaction. But now it fails with another error during runtime.
Gradio Version: 6.2

```
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "G:\pinokio\bin\miniconda\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "G:\pinokio\bin\miniconda\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen  
Traceback (most recent call last):
  File "G:\pinokio\api\e2-f5-test.git\app\env\lib\site-packages\gradio\queueing.py", line 766, in process_events
    response = await route_utils.call_process_api(
  File "G:\pinokio\api\e2-f5-test.git\app\env\lib\site-packages\gradio\route_utils.py", line 355, in call_process_api
    output = await app.get_blocks().process_api(
  File "G:\pinokio\api\e2-f5-test.git\app\env\lib\site-packages\gradio\blocks.py", line 2147, in process_api
    result = await self.call_function(
  File "G:\pinokio\api\e2-f5-test.git\app\env\lib\site-packages\gradio\blocks.py", line 1629, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "G:\pinokio\api\e2-f5-test.git\app\env\lib\site-packages\anyio\to_thread.py", line 61, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "G:\pinokio\api\e2-f5-test.git\app\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2525, in run_sync_in_worker_thread
    return await future
  File "G:\pinokio\api\e2-f5-test.git\app\env\lib\site-packages\anyio\_backends\_asyncio.py", line 986, in run
    result = context.run(func, *args)
  File "G:\pinokio\api\e2-f5-test.git\app\env\lib\site-packages\gradio\utils.py", line 1034, in wrapper
    response = f(*args, **kwargs)
  File "G:\pinokio\api\e2-f5-test.git\app\src\f5_tts\infer\infer_gradio.py", line 290, in basic_tts
    audio_out, spectrogram_path, ref_text_out, used_seed = infer(
  File "G:\pinokio\api\e2-f5-test.git\app\src\f5_tts\infer\infer_gradio.py", line 160, in infer
    ref_audio, ref_text = preprocess_ref_audio_text(ref_audio_orig, ref_text, show_info=show_info)
  File "G:\pinokio\api\e2-f5-test.git\app\src\f5_tts\infer\utils_infer.py", line 353, in preprocess_ref_audio_text
    if not ref_text.strip():
AttributeError: 'NoneType' object has no attribute 'strip'
```
As soon as I expand the Advanced Settings, it's generating the audio and even keeps generating new ones, if I collapse Advance settings again.
But as long as I start f5-tts with collapsed Advanced settings, it keeps failing with this error, no matter how often I try.

**Comment by SWivid** [comment]
@6Morpheus6 will check

**Comment by SWivid** [comment]
I think this may not be with update compatibility issue, but a hanging bug with gradio v6
- https://github.com/gradio-app/gradio/issues/12535
- https://github.com/gradio-app/gradio/milestone/29

Seemingly similar issues:
- https://github.com/gradio-app/gradio/issues/12450
- https://github.com/gradio-app/gradio/issues/12083

Checking if there's a workaround.

**Comment by SWivid** [comment]
> As soon as I expand the Advanced Settings, it's generating the audio and even keeps generating new ones, if I collapse Advance settings again.
> But as long as I start f5-tts with collapsed Advanced settings, it keeps failing with this error, no matter how often I try.

Weird thing is that `Basic-TTS` tab has this bug, but `Voice-Chat` doesn't.

**Comment by SWivid** [comment]
Feel free to test latest version @6Morpheus6 
thanks again~

**Comment by 6Morpheus6** [comment]
Thank you very much @SWivid
From some quick tests everything is working again. :)
